feat: Only submit applications that are in draft or returned status
GenomicDataInfrastructure/gdi-userportal-access-management-service pull request #24
Opened 2024-03-21 08:58 UTC by inderps

2024-03-21 09:24 UTC, EmiPali submitted a review, later dismissed

2024-03-21 10:09 UTC, brunopacheco1 requested changes

2024-03-21 10:09 UTC, brunopacheco1 commented on src/main/java/io/github/genomicdatainfrastructure/daam/services/SubmitApplicationService.java
> +        try {
suggestion: to improve readability, you should move the try/catch that captures `40x` to another function, that retrieves the application if no `40x` happens.

2024-03-21 10:09 UTC, brunopacheco1 commented on src/main/java/io/github/genomicdatainfrastructure/daam/services/SubmitApplicationService.java
> +            if (!application.getApplicationApplicant().getUserid().equals(userId)) {
suggestion: to improve readability, you should move all application content validation to another function.

2024-03-21 10:09 UTC, brunopacheco1 commented on src/main/java/io/github/genomicdatainfrastructure/daam/exceptions/ApplicationNotInCorrectStateException.java
> +        super(message);
suggestion: to improve read,  the message is constant, you should move the text to this classe directly. And you should provide more meaningfull message, like the application id, the current application status and user id.

2024-03-21 10:09 UTC, brunopacheco1 commented on src/main/java/io/github/genomicdatainfrastructure/daam/exceptions/UserNotApplicantException.java
> +        super(message);
suggestion: to improve read,  the message is constant, you should move the text to this classe directly. And you should provide more meaningfull message, like the application id and the user id.

2024-03-21 10:09 UTC, brunopacheco1 commented on src/main/java/io/github/genomicdatainfrastructure/daam/exceptions/ApplicationNotFoundException.java
> +        super(message);
suggestion: to improve read,  the message is constant, you should move the text to this classe directly. And you should provide more meaningfull message, like the application id and the user id.

2024-03-21 10:12 UTC, brunopacheco1 commented on src/main/java/io/github/genomicdatainfrastructure/daam/services/SubmitApplicationService.java
> +            } else {
hint: this `else` is redundant, you could have simply done:

```
if (e.getResponse().getStatus() == 404) {
    throw new ApplicationNotFoundException("Application not found");
}
throw e;
```

2024-03-21 10:17 UTC, brunopacheco1 commented on src/main/java/io/github/genomicdatainfrastructure/daam/mappers/ApplicationNotInCorrectStateExceptionMapper.java
> +        return Response.status(Response.Status.BAD_REQUEST).entity(exception.getMessage()).build();
important: `BAD_REQUEST` is misleading here, it should be either `CONFLICT - 409`, `UNPROCESSABLE_ENTITY - 422` or `PRECONDITION_REQUIRED - 428`. Perhaps the last one fits better.

2024-03-21 13:52 UTC, inderps commented on src/main/openapi/rems.yaml
> +                $ref: '#/components/schemas/ApplicationOverview'
What do you mean by correct schema? ApplicationOverview seems to contain all application entity related properties

2024-03-21 14:14 UTC, inderps commented on src/main/java/io/github/genomicdatainfrastructure/daam/services/SubmitApplicationService.java
> +            if (!application.getApplicationApplicant().getUserid().equals(userId)) {
I looked at the documentaion, they only throw 404. No mention of 403

2024-03-21 14:37 UTC, inderps commented on src/test/java/io/github/genomicdatainfrastructure/daam/api/ApplicationCommandApiImplTest.java
> +  void submitApplication_when_not_applicant() {
The user does exist but not the applicant for this application. 

Regarding error codes, i mixed up somehow

2024-03-21 14:38 UTC, brunopacheco1 commented on src/main/openapi/rems.yaml
> +                $ref: '#/components/schemas/ApplicationOverview'
https://rems-test.rahtiapp.fi/swagger-ui/index.html#/applications/get_api_applications__application_id_

https://rems-test.rahtiapp.fi/swagger-ui/index.html#/applications/get_api_my_applications

Indeed they look similar, but I did not fully review the response model of the two API, they might differ from each other. If you've checked it thoroughly, it should be okay them. Please don't forget to align with @admy7 as he is implementing this endpoint.

2024-03-21 14:42 UTC, brunopacheco1 commented on src/main/java/io/github/genomicdatainfrastructure/daam/services/SubmitApplicationService.java
> +            if (!application.getApplicationApplicant().getUserid().equals(userId)) {
https://github.com/GenomicDataInfrastructure/gdi-userportal-deployment you can run it locally if you want, or mimic  their demo environment request/response API call with Postman or RestClient, https://rems-demo.rahtiapp.fi/

2024-03-21 14:42 UTC, admy7 commented on src/main/openapi/rems.yaml
> +                $ref: '#/components/schemas/ApplicationOverview'
I have used the `Application` schema, the one mentioned in Rems' documentation for the endpoint /api/applications/{application-id}

2024-03-21 14:43 UTC, brunopacheco1 commented on src/main/java/io/github/genomicdatainfrastructure/daam/services/SubmitApplicationService.java
> +            if (!application.getApplicationApplicant().getUserid().equals(userId)) {
I can support on any of these two approach.

2024-03-21 14:50 UTC, brunopacheco1 commented on src/main/java/io/github/genomicdatainfrastructure/daam/exceptions/ApplicationNotInCorrectStateException.java
> +        super("Application " + id + " is not in correct state: " + state);
hint: For the next time, all the messages in the exceptions could be constants. then you could use them as templates for interpolation.

In Java you can do it many ways, for me the simplest is using `.formatted()` functions.

```
private static final String MESSAGE = "Application %s is not in correct state: %s";
...
MESSAGE.formatted(id, state)
...

2024-03-22 07:22 UTC, brunopacheco1 submitted a review, later dismissed
Hey @inderps thanks a lot for you pacience and for promptly improving the code.

2024-03-22 07:22 UTC, brunopacheco1 commented on src/main/java/io/github/genomicdatainfrastructure/daam/mappers/ApplicationNotFoundExceptionMapper.java
> +        return Response.status(Response.Status.NOT_FOUND).entity(exception.getMessage()).build();
Type should mean the same as title, the different is the audience. Type is machine readable - thus should never change - whereas title is human readable and can change overtime.

This is a tiny detail though. We can take care in another PR. Anyway, thanks a lot for taking care of exception handling so fast and so well.

2024-03-22 07:22 UTC, brunopacheco1 commented on src/test/java/io/github/genomicdatainfrastructure/daam/api/ApplicationCommandApiImplTest.java
> +  void submitApplication_when_not_applicant() {
Ah, cool. Good to know there are other users to test.

2024-03-22 08:15 UTC, brunopacheco1 approved these changes

2024-03-22 08:16 UTC, merged