Issue3/improve code
GenomicDataInfrastructure/gdi-userportal-access-management-service pull request #31
Opened 2024-03-25 14:41 UTC by admy7

A couple of improvements for the RetrieveApplicationService: 

- Improve readability 
- Nullability checks
- Add unit test for ApplicationMapper

2024-03-25 14:43 UTC, inderps submitted a review, later dismissed

2024-03-25 14:49 UTC, inderps submitted a review, later dismissed

2024-03-25 17:28 UTC, brunopacheco1 requested changes

2024-03-25 17:28 UTC, brunopacheco1 commented on src/main/java/io/github/genomicdatainfrastructure/daam/mappers/RemsApplicationMapper.java
> +        Optional<UserWithAttributes> applicant = Optional.ofNullable(application
suggestion: to improve readability, you can simply assign to `var` in all the cases.

2024-03-25 17:28 UTC, brunopacheco1 commented on src/main/java/io/github/genomicdatainfrastructure/daam/mappers/RemsApplicationMapper.java
> +                .map(member -> {
important: to improve readability, you should assign this lambda function into a anther private method, the same for the other cases.

2024-03-25 17:28 UTC, brunopacheco1 commented on src/main/java/io/github/genomicdatainfrastructure/daam/mappers/RemsApplicationMapper.java
> +public class RemsApplicationMapper implements ApplicationMapper<Application> {
important: this `RemsApplicationMapper` is a concrete class highly coupled with REMS api implementation. So it should much closer to it.

I liked the idea, but perhaps this interface should be about integration with REMS directly and not just about parsing POJOs / DTOs. I've got an idea how to fix it with clean architecture, but I would like to validate it with you.

2024-03-25 17:28 UTC, brunopacheco1 commented on src/main/java/io/github/genomicdatainfrastructure/daam/utils/ApplicationValidator.java
> +    public Application validate(Long applicationId, String remsApiKey, String userId,
important: this class is doing much more than validating, it's an strategy/adapter to fetch Applications from REMS. Perhaps this one should have a generic interface, and the mapper should be part of it, as composition.

Let's validate this idea together.

2024-03-25 17:28 UTC, brunopacheco1 commented on src/test/java/io/github/genomicdatainfrastructure/daam/mappers/RemsApplicationMapperTest.java
> +        assertEquals(1L, retrievedApplication.getId());
suggestion: Perhaps you could use `AssertJ` to improve the readability of this test.

2024-03-27 10:43 UTC, brunopacheco1 approved these changes

2024-03-27 10:43 UTC, merged